name: grandis
description: This app checking maihama theme park wait times.
version: 2.0.0-dev

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.0+2
  html: ^0.14.0+2
  url_launcher: ^5.1.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
