name: grandis
description: This app checking maihama theme park wait times.
version: 2.0.2-dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  html: ^0.15.0
  cupertino_icons: ^1.0.3
  json_annotation: ^4.3.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.11
  auto_route: ^3.0.4
  url_launcher: ^6.0.12
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
  auto_route_generator: ^3.0.1
  mocktail: ^0.2.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

flutter_icons:
  android: false
  ios: true
  image_path: "android/app/src/main/ic_launcher-playstore.png"
