name: grandis
description: This app checking maihama theme park wait times.
version: 2.0.0-dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  html: ^0.15.0
  cupertino_icons: ^1.0.3
  json_annotation: ^4.3.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  pedantic: ^1.11.1
  build_runner: ^2.1.4
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
