name: build

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: pub get
        run: flutter pub get
      - run: echo "${{secrets.ANDROID_RELEASE_BASE64_KEY}}" | base64 -d > ./keystore.jks
      - run: echo "keyAlias=keystore" >> android/key.properties
      - run: echo "keyPassword=${{secrets.ANDROID_RELEASE_KEY_PASSWORD}}" >> android/key.properties
      - run: echo "storeFile=`pwd`/keystore.jks" >> android/key.properties
      - run: echo "storePassword=${{secrets.ANDROID_RELEASE_STORE_PASSWORD}}" >> android/key.properties
      - name: build apk
        run: flutter build apk --build-number ${GITHUB_RUN_NUMBER}
      - name: deploygate
        if: ${{ !contains(github.head_ref, 'release') }}
        run: |
          curl \
          -H "Authorization: token ${{secrets.DEPLOYGATE_API_KEY}}" \
          -F "file=@build/app/outputs/flutter-apk/app-release.apk" \
          "https://deploygate.com/api/users/yuzumone/apps"
      - name: deploygate and update distribution
        if: ${{ contains(github.head_ref, 'release') }}
        run: |
          curl \
          -H "Authorization: token ${{secrets.DEPLOYGATE_API_KEY}}" \
          -F "file=@build/app/outputs/flutter-apk/app-release.apk" \
          --form-string "distribution_key=c9134daaa2fb6ea07bb05dd7fb1cd05af74d4604" \
          "https://deploygate.com/api/users/yuzumone/apps"
